name: Build Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout SOES
        run: git submodule update --recursive --remote

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Configure CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
            --preset Release \
            -S ${{ github.workspace }} \
            -B ${{ github.workspace }}/build/Release

      - name: Build firmware
        run: |
          cmake --build ${{ github.workspace }}/build/Release \
            --target EcatV2_AX58100_H750_Universal

      - name: Upload ELF artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-elf
          path: ${{ github.workspace }}/build/Release/EcatV2_AX58100_H750_Universal.elf
